spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: ./logs/petpal.log
  level:
    root: INFO
    com.example.petpal: DEBUG

server:
  port: 9090

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

pagination:
  default-page: 0
  default-size: 7

custom-admin:
  first-name: Super
  last-name: Admin
  email: superadmin@example.com
  password: Superadmin123
  phone-number: "+1234567890"
  address: "123 Street"
  role: SUPER_ADMIN

